@extends('admin.layouts.admin-app')
@section('page_title','Seed Targets')

@section('main_headeing','Seed Targets')
@section('sub_headeing','Seed Target Details')

@section('content_section')

<div class="card-header">
    <h3 class="card-title">@yield('sub_headeing')</h3>
    <div class="float-right">
        <a class="btn btn-outline-primary btn-block btn-sm" href="{{ route('seed-targets.index') }}"><i class="fa fa-arrow-left"></i> Back </a>
    </div>
</div>
<div class="card-body">

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="table-responsive">
                <table class="table table-bordered data-table table-striped">
                    <tbody>
                        <tr>
                            <th>Centre Name</th>
                            <td>{{ $seed_target->centre->centre_name }}</td>
                        </tr>
                        <tr>
                            <th>Season</th>
                            <td>{{ $seed_target->season->name }}</td>
                        </tr>
                        <tr>
                            <th>Season</th>
                            <td>{{ $seed_target->crop->name }}</td>
                        </tr>
                        <tr>
                            <th>Target Created On</th>
                            <td>{{ $seed_target->created_at->format('D, d M Y h:i A') }}</td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <table class="table table-bordered data-table table-striped">
                                    <tbody>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Variety Name</th>
                                            <th>Seed Category</th>
                                            <th>Total Seed Quantity (Quintal)</th>
                                            <th>Generated By</th>
                                        </tr>
                                        @if(!empty($seed_target))
                                        @foreach($seed_target->items as $key => $item)
                                        <tr>
                                            <td>{{ $key+1 }}</td>
                                            <td>{{ $item->variety->variety_name }}</td>
                                            <td>{{ $item->category->name }}</td>
                                            <td>{{ $item->total_seed_quantity }}</td>
                                            <td><p class="badge badge-warning">{{ (get_user_role_by_id($item['created_by']) =='user')?'Generated By Centre':'--' }}</p></td>
                                        </tr>
                                        @endforeach
                                        @endif
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

@endsection

@section('additional_js')
<script>

</script>
@endsection